# -*- coding: utf-8 -*-
"""AmeliaRizkiPratiwi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxBASoLG-zvhRDHwuzb0r11olayzQ7Gs
"""

import pandas as pd

df = pd.read_csv('Campus Recruitment.csv')
df.head()

df.info()
df.isnull().sum()

df = pd.get_dummies(df, drop_first=True)
df.head()

df.columns = df.columns.str.strip()

df = df.fillna(0)

X = df.drop('status kelulusan (Bekerja/Belum)_Placed', axis=1)
y = df['status kelulusan (Bekerja/Belum)_Placed']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

importance.head(10)

X = df.drop(['status kelulusan (Bekerja/Belum)_Placed', 'Gaji'], axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
}).sort_values(by='Coefficient', ascending=False)

importance.head(10)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("Accuracy Decision Tree:", accuracy_score(y_test, y_pred_dt))